displayName=Group Attendance
author=y u m e
description=A Group Attendance Tracking Plugin that tracks how long other players are in your vicinity.
tags=clan,attendance,group
plugins=com.GroupAttendanceTracker.GroupAttendanceTrackerPlugin
